dispatch:
  enabled: true
  delay: -1
  # options below requires ProtocolLib or Paper (or fork) core
  required: true
  pack: example
  prompt: "&#fa4943Accept the pack to enjoy a full experience"

dev_server:
  enabled: false
  return_ip: '127.0.0.1'
  port: 3000

patch_packets:
  items: true
  sounds: true