name: ProPack
main: me.nelonn.propack.bukkit.ProPackPlugin
version: ${version}
api-version: 1.17
author: Nelonn
load: STARTUP
description: Resources manager, auto build resource pack
depend: [ Flint ]
softdepend: [ ProtocolLib, PlaceholderAPI ]
