name: ProPack
main: me.nelonn.propack.bukkit.ProPackPlugin
version: ${version}
api-version: 1.17
author: Nelonn
load: STARTUP
description: Modern solution for minecraft resource pack development
website: 'https://github.com/Nelonn/ProPack'
softdepend:
  - PlaceholderAPI

  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
