main: me.nelonn.propack.bukkit.ProPackPlugin
name: ProPack
version: '${version}'
api-version: '1.17'
author: Nelonn
load: STARTUP
description: Modern solution for minecraft resource pack development
website: 'https://github.com/Nelonn/ProPack'
folia-supported: true # maybe not
softdepend:
  - PlaceholderAPI
  - flint-path-lib
  - ProtocolLib
libraries:
  - 'net.kyori:adventure-text-minimessage:4.17.0'
  - 'net.kyori:adventure-text-serializer-plain:4.17.0'
  - 'net.kyori:adventure-text-serializer-legacy:4.17.0'
  - 'net.kyori:adventure-text-serializer-gson:4.17.0'
  - 'net.kyori:adventure-platform-bukkit:4.3.3'
