name: Java CI with Gradle

on:
  pull_request:
    types: [ "closed" ]
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: >-
      (contains(github.event.pull_request.labels.*.name, 'release'))
      && github.event.pull_request.merged == true
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: adopt
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    
    - name: Get version
      id: version
      shell: bash
      run: |
        version=$(grep "^version=" gradle.properties | cut -d'=' -f2)
        echo "::set-output name=version::$version"
    
    - name: Create GitHub Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ steps.version.outputs.version }}
        title: ${{ steps.version.outputs.version }}
        files: |
          propack-api/build/libs/*.jar
          propack-core/build/libs/*.jar
          propack-cli/build/libs/*.jar
          propack-bukkit/build/libs/*.jar
